name: CI Pipeline

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install types-setuptools types-reportlab reportlab black isort
          pip install flake8 mypy bandit pytest
          pip install -e .

      - name: Check formatting with Black
        run: black . --line-length=80

      - name: Check import sorting with isort
        run: isort .

      - name: Lint with flake8
        run: flake8 . --count --show-source --statistics --ignore E203

      - name: Type check with mypy
        run: mypy .

      - name: Security check with Bandit
        run: bandit -r .

      - name: Run tests with pytest
        run: pytest tests/
